language: java
jdk:
- oraclejdk8
deploy:
  provider: bintray
  file: descriptor.json
  user: thomas-siegrist
  key:
    secure: YsbhBhqXWmusLZ1fM+Kx/OkBAgD5XN1E5IoCxnGqm36vyvQwMRBXvtkxh2xfvP4uGpAWpFyCwHcKmWq5itRMkXuXkhrcKMWsDWNt/tDqy+Nhg6dwjDQKXpgkriTH2QjvYOhwayci5CYIl7NGvg1amYbdZ2T6WDtqAhZbrN41GeNJTXn1JqAO5FJ9Rvs3uxncieWS4EkJTs9ZqSrmRo8GjTuK0bcPazf7r/4kR7pNrmZl5HKSFo2/0oZWnOLg9jI2nOfX21bzuSu5MJfPON+voBrv0Z4w8yLUgqZC06TWvmmcgkd45pGqyyuFo26AwIVoZGubUA2qzwSU1LiJAX6m171w396WTX7mnq1ARYTN/a6QWYb00uCycQVuLllBh8unu0AujPSsqbQnnV+4nCARLyK/o5flW9H52zcsHVWqRBJA0L7cLXNYy0AQmRG0+nlBOhGFOLx/VshFwPXFcvgwFL1QnviWTiH2XGN6QKgXEzG4EpgYJssmQf6Pc2xnVAlKsmNAwP468l6NTePhQZbvfUi7hvU1yQxVASBMuM+s2nbuDVXNWkbtPpFQkwVt2uLNXqnZ6FWAjzYeu7ouED/IPAqZqa5sOHzX7Aq+tamcY14O56QIXmDiw4jku6PLdPdVILooNSodAqUQquxoXThl86JplTeWWyCPwAuDZ81pYQ8=
  dry-run: false
